version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: compose/fastapi/Dockerfile
    environment:
      - POSTGRES_DB=countries
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVICE=postgres
      - TEST_POSTGRES_DB=countries
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=countries
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgres/data
    healthcheck :
      test: [ "CMD", "pg_isready", "-q", "-d", "countries", "-U", "postgres" ]
      interval : 5s
      timeout : 5s
      retries : 5
    networks:
      - backend

  yoyo:
    build:
      context: .
      dockerfile: compose/yoyo/Dockerfile
    volumes:
      - .:/backend
    depends_on:
      - app
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data: {}
